version: "3.5"

services:
  api:
    build: .
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - /app/node_modules

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass admin1234
    volumes: 
      - ./data:/data

volumes:
  dbdata6:

